---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: invoices-svc
  name: invoices-svc
  namespace: default
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  fws-invoices_mapping
      prefix: /invoices/
      rewrite: /api/invoices/
      service: invoices-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: invoices-svc
  sessionAffinity: None
  type: ClusterIP